# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MIRROR_PREFIX: https://cloudflaremirrors.com
  BOOTSTRAP_ARCHIVE_NAME: archlinux-bootstrap-x86_64.tar.gz
  ZSTD_BOOTSTRAP_ARCHIVE_NAME: archlinux-bootstrap-x86_64.tar.zst
  BOOTSTRAP_DIR: root.x86_64

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Get bootstrap archive
        run: |
          curl -LO ${{ env.MIRROR_PREFIX }}/archlinux/iso/latest/${{ env.BOOTSTRAP_ARCHIVE_NAME }}
          curl -LO ${{ env.MIRROR_PREFIX }}/archlinux/iso/latest/${{ env.BOOTSTRAP_ARCHIVE_NAME }}.sig

      - name: Verify the archive
        uses: docker://alpine:edge
        with:
          entrypoint: /bin/sh
          args: fetch/verify.sh 

      - name: Re-compress bootstrap archive
        run: zstdcat ${{ env.BOOTSTRAP_ARCHIVE_NAME }} | zstdmt -o ${{ env.ZSTD_BOOTSTRAP_ARCHIVE_NAME }} -

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bootstrap-archive
          path: ${{ env.ZSTD_BOOTSTRAP_ARCHIVE_NAME }}
          if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Download bootstrap archive
        uses: actions/download-artifact@v3
        with:
          name: bootstrap-archive

      - name: get status
        run: |
          ls -alh
          pwd
          tar --preserve-permissions xf ${{ env.ZSTD_BOOTSTRAP_ARCHIVE_NAME }}
          ls -alh ${{ env.BOOTSTRAP_DIR }}
          ansible --version
          ansible-galaxy --version

  make-subvol:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download bootstrap archive
        uses: actions/download-artifact@v3
        with:
          name: bootstrap-archive

      - name: get status
        run: |
          mkfs.btrfs --help
          truncate --help
