# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install dep packages
        if: false
        run: |
          sudo apt-get update
          sudo apt-get install --yes nettle-dev
          cargo install sequoia-sq

      # Runs a set of commands using the runners shell
      - name: Get bootstrap archive
        run: |
          curl -LO https://cloudflaremirrors.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.gz
          curl -LO https://cloudflaremirrors.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.gz.sig

      - name: Verify the archive
        if: false
        run: |
          sq wkd get pierre@archlinux.org -o release-key.pgp
          sq verify --signer-file release-key.pgp --detached archlinux-bootstrap-x86_64.tar.gz.sig archlinux-bootstrap-x86_64.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bootstrap-archive
          path: archlinux-bootstrap-x86_64.tar.gz
          if-no-files-found: error
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download bootstrap archive
        uses: actions/download-artifact@v3
        with:
          name: bootstrap-archive
      - name: get status
        run: |
          ls -alh
          pwd

